cd language:
    node_js
node_js:
    - 0.8
branches:
    only:
        - master
env:
    global:
        - secure: "B2xi2qBwg0omjXBZp7mTgqNzl+QeTGlq8vY+lnZR1jQ4iMTafrAopAK94AQj3Ati+EnN7XZvDRa/hM/g9VenUS2aSYhcHxPl0UPQyoDKtK3hS1qsXdrF6qk2i7gziItwL00ZtLq66Oif3JFHJrhstFwbHOX/8vCiZjD5fRWp0kU="
        - GH_OWNER: lwndev
        - GH_PROJECT_NAME: video-story-concept.git
before_script:
    # install dependencies
    - gem update --system
    - gem install compass
    - npm install -g grunt-cli bower
script:
    # We want to gate on passing tests and a successful build
    - npm install
    - bower install
    - grunt
after_success:
    - git submodule add -b gh-pages https://${GH_OAUTH_TOKEN}@github.com/${GH_OWNER}/${GH_PROJECT_NAME} site > /dev/null 2>&1
    - cd site
    - if git checkout gh-pages; then git checkout -b gh-pages; fi
    - git rm -r .
    - cp -R ../dist/* .
    - cp ../dist/.* .
    - git add -f .
    - git config user.email "leif@lwndev.com"
    - git config user.name "lwndev"
    - git commit -am "adding the yeoman build files to gh-pages [ci skip]"
    - git push https://${GH_OAUTH_TOKEN}@github.com/${GH_OWNER}/${GH_PROJECT_NAME} HEAD:gh-pages > /dev/null 2>&1
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"